[package]
name = "autoupdate"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
indicatif = "0.17.8"
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde = { version = "1.0.213", features = ["derive"] }
